### ISSUE TITLE
Should we make `ebirdloccheck` an "external" function to be imported with rebird?

### ISSUE THREAD

**Issue by sebpardo** [ateucher/rebird#10]
Might be of use to others, particularly given that `ebirdregion` uses the same regions. Might have to reconsider renaming to `ebirdregioncheck` as `ebirdloc` is not for regions but hotspots and other type of locations that are not countries, states, or counties...

**Comment by ateucher** [comment]
Good idea re: renaming. I'm not sure about other uses besides other ebird functions potentially calling it, but exporting it can't hurt I suppose.
