### ISSUE TITLE
replace stop_for_status()

### ISSUE THREAD

**Issue by sebpardo** [ateucher/rebird#5]
Doesn't work as even with incorrect queries that return no observations the request is still successful with status 200.

**Comment by ateucher** [comment]
I think we want to keep it for if the ebird website is actually down etc, and add more fulsome parameter checking in `get_freq` (including #2 )

**Comment by sebpardo** [comment]
Good point. 

I wrote a location checking function: https://github.com/ateucher/rebird/blob/frequency-data/R/eloc_check.R and added it to `get_freq` (db394ef5ce89570f6d9ccf474690f578b7a84ef2)

**Comment by ateucher** [comment]
See #2
