### ISSUE TITLE
Write some tests

### ISSUE THREAD

**Issue by ateucher** [ateucher/rebird#7]
We should write a few simple tests for the two new functions. We should follow the templates in https://github.com/ateucher/rebird/tree/frequency-data/tests/testthat

**Comment by ateucher** [comment]
I've started by writing some for `ebirdloccheck`: https://github.com/ateucher/rebird/blob/frequency-data/tests/testthat/test-ebirdfreq.R

**Comment by sebpardo** [comment]
9284782bfac2ee4c4a2319322845087d7be78961

**Comment by sebpardo** [comment]
9284782bfac2ee4c4a2319322845087d7be78961
