### ISSUE TITLE
Make ebirdfreq fail when start and end years are not numeric

### ISSUE THREAD

**Issue by sebpardo** [ateucher/rebird#8]
Currently, `ebirdfreq("counties", "CA-BC-CP", "US", "US")` will be successful and return real sightings (!!!). On the other hand `ebirdfreq("counties", "CA-BC-CP", "US", "US", "US")` will result in a server error, which makes me think that the bYear and eYear fields get coerced to numeric or get ignored when not numeric, with this not being the case for bMonth and eMonth and failing when these are not numeric.

**Comment by ateucher** [comment]
:+1: We should definitely do this (always a good idea to verify inputs, even though it can be tedious)
