### ISSUE TITLE
Make ebirdfreq check that hotspot `loc` is in the format of "L1..."

### ISSUE THREAD

**Issue by sebpardo** [ateucher/rebird#9]
We should make `ebirdfreq("hotspots", "foo123")` return an error saying that hotspot doesn't conform to desired pattern of "L" appended with a number. Right now it only gives a warning because of no returned sightings. Note that "L1" is actually a valid hotspot in Alberta.

**Comment by ateucher** [comment]
Do all hotspots globally begin with L? Is there a way to verify that?

**Comment by sebpardo** [comment]
I had a quick look across al continents and all hotspot I checked begin with an L followed by a number up to 7 digits long. I think the only way to verify that would be to scrape the API but it wouldn't be pretty and would probably require hundreds if not 1000s of queries.

**Comment by ateucher** [comment]
Perfect, I think that'll do. So could use something like `grepl("^L\\d+$", loc)`?

**Comment by sebpardo** [comment]
Based on my very limited knowledge of regexp, I think that works fine. If we wanted to put a limit on how many numeric characters there can be to avoid extremely long values such as "L123123123123123", then we could do `grepl("^L\\d{1,8}$", loc)`. When looking through I never saw any values above one or two million. I doubt there will ever be more than 99.9 million hotspots; however if that eventually happens we could change it to `d{1,9}` when we are ninety or so :older_man:

**Comment by ateucher** [comment]
Yup, could do that for sure - I just wasn't sure what the upper limit was.
